services:
  chroma:
    image: chromadb/chroma:1.0.20
    container_name: chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ANONYMIZED_TELEMETRY=False 
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma/.chromadb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_api
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - CHROMA_TENANT=default_tenant
      - CHROMA_DATABASE=default_database
      - CHROMA_COLLECTION=resoluciones_cu 
      - CHROMA_DISTANCE=cosine

      # LMStudio connection
      - LLM_BASE_URL=http://host.docker.internal:1234/v1
      - LLM_MODEL=openai/gpt-oss-20b
      - LLM_API_KEY=notused
      - MAX_ANSWER_CHUNKS=8
      - TOP_K=50
      - TEMPERATURE=0.2
      - MAX_TOKENS=1600

      # Document chunking settings
      - CHUNK_MAX_TOKENS=600
      - CHUNK_OVERLAP_TOKENS=50
      - CHUNK_USE_SPACY=1
      - SPACY_MODEL=es_core_news_sm
      - SPACY_MAX_LENGTH=5000000

      # BM25 settings
      - BM25_INDEX_DIR=/data/whoosh_index
      - K_LEX=100
      - RERANK_TOP=24
      - RRF_K=30

      #Embeddings via LMStudio
      - EMBED_BASE_URL=http://host.docker.internal:1234/v1
      - EMBED_MODEL=text-embedding-nomic-embed-text-v1.5@f32
      - EMBED_API_KEY=notused

      #MODS
      - USE_HYDE=1
      - USE_MULTIQUERY=1
      - MULTIQUERY_N=3

    volumes:
      - ./app:/app
      - ./data:/data
    depends_on:
      - chroma
    ports:
      - "8099:8099"
