services:
  chroma:
    image: chromadb/chroma:1.0.20
    container_name: chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ANONYMIZED_TELEMETRY=False
      - ALLOW_RESET=True
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma/.chromadb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  
  embedd-service:
    build:
      context: ./embed_service
      dockerfile: Dockerfile
    container_name: embed-service
    environment:
      - EMBED_PORT=8010
      - EMBED_MODEL=text-embedding-nomic-embed-text-v1.5
      - DOWNSTREAM_URL=http://host.docker.internal:1234/v1
      - DOWNSTREAM_API_KEY=notused
    ports:
      - "8010:8010"
    volumes:
      - ./embed_service:/app
      - ./data:/data
    restart: unless-stopped

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: rag_api
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - CHROMA_TENANT=default_tenant
      - CHROMA_DATABASE=default_database
      - CHROMA_COLLECTION=resoluciones_cu 
      - CHROMA_DISTANCE=cosine

      # LMStudio connection
      - LLM_BASE_URL=http://host.docker.internal:1234/v1
      - LLM_MODEL=openai/gpt-oss-20b
      - LLM_API_KEY=notused
      - MAX_ANSWER_CHUNKS=8
      - TOP_K=50
      - TEMPERATURE=0.2
      - MAX_TOKENS=1600

      # Document chunking settings
      - CHUNK_MAX_TOKENS=1000
      - CHUNK_OVERLAP_TOKENS=0
      - CHUNK_USE_SPACY=1
      - SPACY_MODEL=es_core_news_sm
      - SPACY_MAX_LENGTH=5000000

      # BM25 settings
      - BM25_INDEX_DIR=/data/whoosh_index
      - K_LEX=200
      - RERANK_TOP=24
      - RRF_K=60

      #Embeddings via internal service
      - EMBED_BASE_URL=http://embed-service:8010
      - EMBED_MODEL=text-embedding-nomic-embed-text-v1.5
      - EMBED_API_KEY=notused

    volumes:
      - ./app:/app
      - ./data:/data
    depends_on:
      - chroma
      - embedd-service
    ports:
      - "8099:8099"
    restart: unless-stopped
