version: '3.8'
services:
  chroma:
    image: chromadb/chroma:1.0.20
    container_name: chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ANONYMIZED_TELEMETRY=False 
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma/.chromadb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_api
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - CHROMA_TENANT=default_tenant
      - CHROMA_DATABASE=default_database
      - CHROMA_COLLECTION=resoluciones_cu 

      # LMStudio connection
      - LLM_BASE_URL=http://host.docker.internal:1234/v1
      - LLM_MODEL=mistral-7b-instruct-v0.2
      - LLM_API_KEY=notused
      - MAX_ANSWER_CHUNKS=6
      - TOP_K=12

      #Embeddings via LMStudio
      - EMBED_BASE_URL=http://host.docker.internal:1234/v1
      - EMBED_MODEL=nomic-ai/nomic-embed-text-v1.5-GGUF
      - EMBED_API_KEY=notused

    volumes:
      - ./app:/app
      - ./data:/data
    depends_on:
      - chroma
    ports:
      - "8099:8099"
